### ISSUE TITLE
Request: add ability to download updates straight from NUS

### ISSUE THREAD

**Issue by sora10pls** [llakssz/FunKiiU#14]
Update Data for games from NUS have a signed ticket already included, and not every game update is available on the titlekeys database (example: Mario Kart 8 USA). Perhaps allow the user to download updates straight from NUS if they add `-nus` at the end of their command?

**Comment by llakssz** [comment]
it already does this :)

**Comment by sora10pls** [comment]
Ah, that makes a lot more sense. Totally didn't try using -onlinetickets hahaha

Thanks for clarifying!

**Comment by sora10pls** [comment]
Actually scratch that... upon testing it out, it still didn't download the update. I wrote the following command:

`$ python FunKiiU.py -title 0005000E1010EC00 -onlinetickets`
![image](https://cloud.githubusercontent.com/assets/17801814/19906691/2b996726-a052-11e6-8f41-596776bcfb84.png)

Mario Kart 8 USA update is not on the title keys database, and as shown in the picture, it still attempts to download from it.

**Comment by llakssz** [comment]
Ok, now this has turned into a bug! 🐛 

Either way, I still meant for data to be checked online from the keysite because it can be nice to get things like the name and region, if the site does have a listing for the update.


--
Thankfully I spotted that one easily, it could have turned into much longer!
You are using uppercase characters, I always use lowercase.
(Of course I thought we were converting to lowercase always, but no.)

An easy fix.

**Comment by llakssz** [comment]
fixed, uppercase title ids are not a problem
