### ISSUE TITLE
Query: Execute on Android / QPython options.

### ISSUE THREAD

**Issue by SumGaea** [llakssz/FunKiiU#32]
Hi. Thanks for FunkiiU & also to the FunkiiUI team. Both work very well with python.

Been trying to get either of the above working on QPython (https://github.com/qpython-android/qpython/releases/tag/1.2.7). Tried funkiiu.py (lowercase yes) in /qpython/scripts/ and /qpython/projects/FunKiiU/ (rename to main.py), no difference.

Having more luck with just FunkiiU (no tcl/tk headaches), but I can't seem to find a working way to pass arguments in QPython. Keeps exiting with credits as on Win/Mac/Linux python without arguments.

I'm willing to hard code arguments per title, it's just that I'm unsure where what to replace / comment out.
Otherwise perhaps there's an easier fix to make them play nice? Open to suggestions.

Thanks again.

**Comment by SumGaea** [comment]
Some progress. Setting the defaults in this section was what I was looking for. Lines 43-64

```
parser.add_argument('-title', nargs='+', dest='titles', default=[],
                    help='Give TitleIDs to be specifically downloaded')
```
becomes
```
parser.add_argument('-title', nargs='+', dest='titles', default=['0123456789etcetc'],
                    help='Give TitleIDs to be specifically downloaded')
```
Now to work around the file IO / permissions errors.

**Comment by Nemris** [comment]
@SumGaea

I'm pretty late, but do know that it's possible to run FunKiiU via the Termux app, having installed either Python 2 or 3 via `apt`, with no code editing required.

You are certain to meet permission issues if you try to save contents in an external SD card on Android 6 or greater, due to Google's new policies on SD card write access. This can be worked around with root privileges. Unless you have them, you are restricted to `/sdcard` and its subdirectories.

**Comment by SumGaea** [comment]
Termux is the way. Thanks @DMSalesman. Closing.
